import Link from "next/link";
import "./globals.css";
import { ErrorWrapper } from "./error-wrapper";

// *****Static metadata object********
export const metadata = {
  title: {
    default: "Nazil - NextJS",
    // template : "ND - %s"
    template: "%s | ND",
  },
  description: "Generated by Next.js",
};

export default function NonAuthLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header className="bg-blue-400 p-4 flex justify-end gap-4">
          <Link className="bg-white p-2 rounded-2xl" href={"/"}>
            Home 🏠
          </Link>
          <Link className="bg-white p-2 rounded-2xl" href={"/products"}>
            Products
          </Link>
        </header>

        <ErrorWrapper>{children}</ErrorWrapper>

        <footer className="bg-amber-400 p-4">
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
